name = "GaussianSplittingLibrary"
uuid = "35187416-db38-4eaf-a5fe-bcd39acf1f0e"
authors = ["liamblake <liam.blake@adelaide.edu.au>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
